### ISSUE TITLE
Error on backspace to prev line.

### ISSUE THREAD

**Issue by ozeron** [richrace/highlight-line#61]
1. Backspace to the previus line from first position in line to the middle of previous. In the center of text.

![Example]
(http://g.recordit.co/vOJIXdx3y5.gif)

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: [highlight-line](https://github.com/richrace/highlight-line) package, v0.9.3

### Stack Trace

Uncaught Error: No line exists for row 64. Last screen row: 63

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:234

Error: No line exists for row 64. Last screen row: 63
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateLinesState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:234:17)
  at TextEditorPresenter.module.exports.TextEditorPresenter.didDestroyDecoration (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:979:16)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:932:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Decoration.module.exports.Decoration.destroy (/Applications/Atom.app/Contents/Resources/app/src/decoration.js:59:20)
  at /Applications/Atom.app/Contents/Resources/app/src/decoration.js:46:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroyed (/Applications/Atom.app/Contents/Resources/app/src/marker.js:264:20)
  at /Applications/Atom.app/Contents/Resources/app/src/marker.js:51:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:318:20)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app/src/marker.js:62:25)
  at HighlightLineView.module.exports.HighlightLineView.resetBackground (/Users/rubydev/.atom/packages/highlight-line/lib/highlight-line-view.coffee:42:18)
  at HighlightLineView.module.exports.HighlightLineView.updateSelectedLine (/Users/rubydev/.atom/packages/highlight-line/lib/highlight-line-view.coffee:37:6)
  at atom-workspace.<anonymous> (/Users/rubydev/.atom/packages/highlight-line/lib/highlight-line-view.coffee:1:1)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at TextEditorView.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:201:49)
  at CallbackQueue.mixInto.notifyAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.replaceState (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:878:20)
  at [object Object].ReactCompositeComponentMixin.setState (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:850:10)
  at [object Object].module.exports.React.createClass.focused (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:381:14)
  at [object Object].boundMethod [as focused] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at atom-text-editor.TextEditorElement.shadowRootBlurred (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:215:31)
  at Object.jQuery.event.trigger (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4629:18)
  at atom-text-editor.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5124:17)
  at Function.jQuery.extend.each (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:590:23)
  at TextEditorView.jQuery.fn.jQuery.each (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:237:17)
  at TextEditorView.jQuery.fn.extend.trigger (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5123:15)
  at TextEditorView.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:56:28)
  at TextEditorView.jQuery.fn.(anonymous function) [as focus] (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:6733:9)
  at AutocompleteView.module.exports.AutocompleteView.cancel (/Users/rubydev/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:143:19)
  at AutocompleteView.cancel (/Users/rubydev/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:1:1)
  at AutocompleteView.module.exports.AutocompleteView.onChanged (/Users/rubydev/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:226:8)
  at /Users/rubydev/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:1:1
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:595:12)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:507:12)
  at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:604:19)
  at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:561:37)
  at Selection.module.exports.Selection.delete (/Applications/Atom.app/Contents/Resources/app/src/selection.js:532:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:808:35
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:826:27
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:819:19)
  at TextEditor.module.exports.TextEditor.delete (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:807:19)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:delete (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:425:28)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:305:34
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
  2x -1:21.0 core:delete (atom-text-editor.editor.is-focused)
  2x -1:09.3 core:save (atom-text-editor.editor.is-focused)
     -0:56.9 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:56.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:52.2 core:move-left (atom-text-editor.editor.is-focused)
     -0:51.7 core:save (atom-text-editor.editor.is-focused)
 33x -0:36.2 core:delete (atom-text-editor.editor.is-focused)
     -0:25.8 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.1 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:18.1 core:cancel (atom-text-editor.editor.is-focused)
     -0:13.1 core:move-left (atom-text-editor.editor.is-focused)
  9x -0:12.5 core:undo (atom-text-editor.editor.is-focused)
     -0:06.1 core:save (atom-text-editor.editor.is-focused)
  2x -0:05.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.1 core:save (atom-text-editor.editor.is-focused)
  5x -0:01.6 core:delete (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
atom-color-highlight, v3.0.8
autocomplete-plus, v2.1.6
autocomplete-plus-async, v0.22.0
ember-snippets, v1.0.0
emmet, v2.3.3
git-projects, v1.8.0
highlight-line, v0.9.3
line-ending-converter, v1.0.0
linter, v0.11.1
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
ruby-block, v0.2.2
ruby-block-converter, v3.1.0
ruby-define-method, v0.2.0
ruby-slim, v0.2.0
script, v2.16.0

# Dev
No dev packages
```

**Comment by richrace** [comment]
Have you been able to replicate this? I can't seem to do it here.

**Comment by vicksonzero** [comment]
steps:
1. new document, type abc<enter>def
2. move cursor to before 'd'
3. press <backspace>

expected: becomes abcdef
actual: becomes abcdef, plus this error

==========

alternative steps:
1. new document, type abc<enter>def
2. move cursor to after 'c'
3. press <delete>

expected: becomes abcdef
actual: becomes abcdef, plus this error

**Comment by vicksonzero** [comment]
ok even more simple:

steps:
1. new document, press [enter]
2. press [backspace]

or steps:
1. new document, press [enter]
2. press left arrow
2. press [delete]

**Comment by AndreasPizsa** [comment]
+1 here, unfortunately. I hope this report is helpful.

[Enter steps to reproduce below:]

1. Go to first column of a line
2. Press backspace

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.3
**Thrown From**: [highlight-line](https://github.com/richrace/highlight-line) package, v0.9.3

### Stack Trace

Uncaught Error: No line exists for row 13. Last screen row: 12

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:234

Error: No line exists for row 13. Last screen row: 12
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateLinesState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:234:17)
  at TextEditorPresenter.module.exports.TextEditorPresenter.didDestroyDecoration (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:979:16)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:932:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Decoration.module.exports.Decoration.destroy (/Applications/Atom.app/Contents/Resources/app/src/decoration.js:59:20)
  at /Applications/Atom.app/Contents/Resources/app/src/decoration.js:46:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroyed (/Applications/Atom.app/Contents/Resources/app/src/marker.js:264:20)
  at /Applications/Atom.app/Contents/Resources/app/src/marker.js:51:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:318:20)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app/src/marker.js:62:25)
  at HighlightLineView.module.exports.HighlightLineView.resetBackground (/Users/apizsa/.atom/packages/highlight-line/lib/highlight-line-view.coffee:42:18)
  at HighlightLineView.module.exports.HighlightLineView.updateSelectedLine (/Users/apizsa/.atom/packages/highlight-line/lib/highlight-line-view.coffee:37:6)
  at atom-workspace.<anonymous> (/Users/apizsa/.atom/packages/highlight-line/lib/highlight-line-view.coffee:1:1)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at TextEditorView.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:201:49)
  at CallbackQueue.mixInto.notifyAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.replaceState (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:878:20)
  at [object Object].ReactCompositeComponentMixin.setState (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:850:10)
  at [object Object].module.exports.React.createClass.focused (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:381:14)
  at [object Object].boundMethod [as focused] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at atom-text-editor.TextEditorElement.shadowRootBlurred (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:215:31)
  at Object.jQuery.event.trigger (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4629:18)
  at atom-text-editor.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5124:17)
  at Function.jQuery.extend.each (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:590:23)
  at TextEditorView.jQuery.fn.jQuery.each (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:237:17)
  at TextEditorView.jQuery.fn.extend.trigger (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5123:15)
  at TextEditorView.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:56:28)
  at TextEditorView.jQuery.fn.(anonymous function) [as focus] (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:6733:9)
  at AutocompleteView.module.exports.AutocompleteView.cancel (/Users/apizsa/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:143:19)
  at AutocompleteView.cancel (/Users/apizsa/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:1:1)
  at AutocompleteView.module.exports.AutocompleteView.onChanged (/Users/apizsa/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:226:8)
  at /Users/apizsa/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:1:1
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:595:12)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:507:12)
  at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:604:19)
  at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:561:37)
  at Selection.module.exports.Selection.backspace (/Applications/Atom.app/Contents/Resources/app/src/selection.js:494:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:814:26
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:826:27
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:819:19)
  at TextEditor.module.exports.TextEditor.backspace (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:813:19)
  at TextEditor.object.(anonymous function) [as backspace] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:backspace (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:422:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:305:34
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1195:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
     -0:23.0 refactor:done (atom-text-editor.editor.is-focused)
     -0:23.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:22.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:21.8 editor:indent (atom-text-editor.editor.is-focused)
     -0:20.5 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  4x -0:20.2 editor:indent (atom-text-editor.editor.is-focused)
     -0:17.2 core:move-down (atom-text-editor.editor.is-focused)
     -0:17.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:15.7 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:15.1 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:14.6 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.3 editor:indent (atom-text-editor.editor.is-focused)
     -0:11.8 refactor:done (atom-text-editor.editor.is-focused)
     -0:11.8 editor:newline (atom-text-editor.editor.is-focused)
     -0:10.8 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  7x -0:10.5 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "autosave",
      "autocomplete",
      "snippets",
      "linter-jsl",
      "linter-jshint",
      "linter-coffeelint",
      "atom-lint",
      "linter-eslint",
      "linter"
    ],
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.7.0
atom-beautify, v0.21.3
atom-handlebars, v0.4.0
autocomplete-emojis, v1.0.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
autocomplete-plus-async, v0.22.0
coffee-navigator, v0.0.15
coffee-refactor, v0.6.2
color-picker, v1.4.4
docs-snippets, v0.8.0
editorconfig, v0.3.0
file-icons, v1.4.11
highlight-line, v0.9.3
js-refactor, v0.3.0
jumpy, v2.0.2
language-gherkin, v0.3.0
language-jade, v0.3.0
linter-csslint, v0.0.11
linter-js-yaml, v1.0.0
linter-php, v0.0.11
linter-phpcs, v0.0.12
linter-scss-lint, v0.0.14
open-last-project, v0.3.1
pretty-json, v0.3.2
refactor, v0.4.1
script, v2.16.0
travis-ci-status, v0.11.2
valign, v0.13.4
wakatime, v4.0.0

# Dev
markdown-preview, v0.100.0
```

**Comment by richrace** [comment]
I still cannot reproduce this.

**Comment by ScreenDriver** [comment]
:+1: 
Same here: Mac OS X 10.10.2 + Atom 0.186.0

**Comment by richrace** [comment]
Still happenning?

**Comment by ScreenDriver** [comment]
For me it's working at the moment.
