### ISSUE TITLE
Failed to load the highlight-line package

### ISSUE THREAD

**Issue by lancelafontaine** [richrace/highlight-line#66]
Running Atom 0.187.0 on Ubuntu 14.04:

1. After cloning the repository into the ~/.atom/packages/ directory, start Atom.
2. Error occurs.

**Atom Version**: 0.187.0
**System**: linux 3.13.0-48-generic
**Thrown From**: [highlight-line](https://github.com/richrace/highlight-line) package, v0.10.1

### Stack Trace

Failed to load the highlight-line package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/lance/.atom/packages/highlight-line/lib/highlight-line-view.coffee:1:10)
  at Object.<anonymous> (/home/lance/.atom/packages/highlight-line/lib/highlight-line-view.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/lance/.atom/packages/highlight-line/lib/highlight-line.coffee:2:21)
  at Object.<anonymous> (/home/lance/.atom/packages/highlight-line/lib/highlight-line.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:672:34)
  at /usr/share/atom/resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:355:14)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:622:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:51:25)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "graphite-ui",
      "monokai"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "emmet-atom"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-open-recent, v2.2.0
atom-pair, v1.0.1
atom-sublime-select, v1.2.3
autoclose-html, v0.15.0
autocomplete-plus, v2.6.0
file-icons, v1.5.2
graphite-ui, v0.14.1
highlight-line, v0.10.1
latex, v0.20.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-flake8, v1.3.0
linter-jshint, v0.1.0
linter-php, v0.0.11
linter-shellcheck, v0.0.7
linter-tidy, v1.0.0
minimap, v4.6.0
monokai, v0.12.0
pdf-view, v0.17.0
save-session, v0.12.3
script, v2.18.0
synced-sidebar, v0.2.3
trailing-spaces, v0.2.4

# Dev
No dev packages
```

**Comment by richrace** [comment]
You need to run update package dependencies.
