### ISSUE TITLE
Uncaught Error: No screen line exists when converting buffer row to screen row

### ISSUE THREAD

**Issue by KoganezawaRyouta** [richrace/highlight-line#68]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.9.5
**Thrown From**: [highlight-line](https://github.com/richrace/highlight-line) package, v0.10.2

### Stack Trace

Uncaught Error: No screen line exists when converting buffer row to screen row

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1029

Error: No screen line exists when converting buffer row to screen row
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1029:17)
  at DisplayBuffer.module.exports.DisplayBuffer.screenRangeForBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:884:20)
  at Marker.module.exports.Marker.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:138:33)
  at Selection.module.exports.Selection.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:88:26)
  at Selection.module.exports.Selection.isSingleScreenLine (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:169:19)
  at HighlightLineView.module.exports.HighlightLineView.handleMultiLine (/Users/ryoutakoganezawa/.atom/packages/highlight-line/lib/highlight-line-view.coffee:74:24)
  at HighlightLineView.handleMultiLine (/Users/ryoutakoganezawa/.atom/packages/highlight-line/lib/highlight-line-view.coffee:1:1)
  at HighlightLineView.module.exports.HighlightLineView.showHighlight (/Users/ryoutakoganezawa/.atom/packages/highlight-line/lib/highlight-line-view.coffee:52:6)
  at HighlightLineView.showHighlight (/Users/ryoutakoganezawa/.atom/packages/highlight-line/lib/highlight-line-view.coffee:1:1)
  at HighlightLineView.module.exports.HighlightLineView.updateSelectedLine (/Users/ryoutakoganezawa/.atom/packages/highlight-line/lib/highlight-line-view.coffee:42:6)
  at /Users/ryoutakoganezawa/.atom/packages/highlight-line/lib/highlight-line-view.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:338:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:298:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:189:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "atom-dark-ui",
      "Wild-Cherry"
    ]
  },
  "highlight-line": {
    "enableSelectionBorder": true,
    "enableUnderline": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
Wild-Cherry, v0.4.0
atom-color-highlight, v3.0.9
atom-runner, v2.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.1
autocomplete-snippets, v1.3.0
file-icons, v1.5.4
flex-toolbar, v0.1.10
git-log, v0.3.0
highlight-line, v0.10.2
highlight-selected, v0.9.2
japanese-wrap, v0.2.7
language-html, v0.34.0
language-ruby, v0.52.0
linter, v0.12.1
linter-bootlint, v0.0.5
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-erb, v0.1.0
linter-eslint, v0.5.3
linter-flow, v0.1.4
linter-htmlhint, v0.0.13
linter-js-yaml, v1.0.0
linter-jscs, v1.10.0
linter-jshint, v0.1.2
linter-jsxhint, v0.1.1
linter-less, v0.3.1
linter-rubocop, v0.2.3
linter-ruby, v0.1.4
linter-scss-lint, v0.0.14
linter-tidy, v1.0.0
minimap, v4.7.6
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.1
minimap-selection, v4.2.0
project-manager, v1.15.5
regex-railroad-diagram, v0.7.4
save-session, v0.13.5
script, v2.19.0
show-ideographic-space, v0.1.6
symbols-tree-view, v0.9.2
syntax-settings, v0.7.1
tabs-to-spaces, v0.9.2
toolbar, v0.0.16
toolbar-main, v0.0.6
trailing-spaces, v0.2.5
web-view, v0.3.0

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
Steps to reproduce:
with such selection, try to press backspace/delete on mac, issue appears only sometimes.
![image](https://cloud.githubusercontent.com/assets/193864/7907686/0908ebb8-086f-11e5-9e8b-c2e036dc1acd.png)

**Comment by richrace** [comment]
Is this still an issue? I'm still yet able to repeat it.
